# DATABASE
# PATHS

# DATABASE
VAR_DB_HOST = "115.159.197.66"
VAR_DB_NAME = "myblog"
VAR_DB_USER = "myblog"
VAR_DB_PASSWORD = "Ln525SuTr7reDYuP"

# PATHS
VAR_IMAGE_UPLOAD = ""
VAR_CONFIG_FILE = "./config/site.cfg"

